on:
  pull_request:

jobs:
  send_data_to_whatsapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send data to whatsapp
        env:
          DATA: matan
        run: | 
          echo matan
