on:
  pull_request:

jobs:
  send_data_to_whatsapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send data to whatsapp
        env:
          TWILIO_ACCOUNT_SID: matan
          TWILIO_AUTH_TOKEN: TWILIO_AUTH_TOKEN
          TWILIO_PHONE_NUMBER: asd
          MY_PHONE_NUMBER: asd
        run: |
          npm start
