on:
  pull_request:

jobs:
  send_data_to_whatsapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send data to whatsapp
        with:
          env:
            - name: DATA
              value: $DATA
            - name: TO
              value: $TO
            - name: FROM
              value: $FROM

        run:
        | 
        echo matan